print("Welcome to the tip calculator")
bill = input("What was the total bill? ")
tip = input("How much tip would you like to give? 10, 12, or 15? ")
total_with_tip = int(bill) + (int(bill) * (int(tip)/100)) 
how_many_people = input("How many people to split the bill? ")
each_person_amount= float(total_with_tip) / int(how_many_people)
print(f"Each person should pay: $ {round(each_person_amount,2)}")
